
# ALL
path = 'all_participants/'
file_all_orderby_totaltime = path + 'all_orderby_totaltime.csv'
file_excludetask4 = path + 'allParticipantsResultExcludeTask4.csv'
file_excludetask4_orderby_totaltime = path + 'allExcludeTask4_Orderby_totaltime.csv'
file_excludetask4_orderby_totalcorrect = path + 'allExcludeTask4_Orderby_total_correct_elements.csv'

file_excludetask4_orderby_age_filterlessthan2000 = path + 'allExcludeTask4totaltimebiggerthan2000orderbyparticipant__age.csv'

# Interupted
path = 'was_interupted_participants/'
file_was_interupted_orderedby_difficulty = path + 'allParticipants_wasinterupted_orderby_difficulty.csv'

# Not interupted
path = 'was_not_interupted/'
file_all_exclude4_orderby_totaltime = path + 'all_was_not_interupted_exclude4_orderby_taskresult__totaltime.csv'
file_all_exclude4_orderby_totalcorrect = path + 'all_was_not_interupted_exclude4_orderby_taskresult__total_correct_elements.csv'
file_experienced_exclude4_orderby_totaltime = path + 'experienced_was_not_interupted_exclude4_orderby_taskresult__totaltime.csv'
file_experienced_exclude4_orderby_totalcorrect = path + 'experienced_was_not_interupted_exclude4_orderby_taskresult__total_correct_elements.csv'
file_inexperienced_exclude4_orderby_totaltime = path + 'inexperienced_was_not_interupted_exclude4_orderby_taskresult__totaltime.csv'
file_inexperienced_exclude4_orderby_totalcorrect = path + 'inexperienced_was_not_interupted_exclude4_orderby_taskresult__total_correct_elements.csv'

# Experienced
path_e = 'experienced_participants/'
file_experienced_orderby_totaltime = path_e + 'experiencedResult_orderby_totaltime.csv'
file_experienced_orderby_totaltime_exclude4 = path_e + 'experiencedResultExcludeTask4_orderby_totaltime.csv'
file_experienced_orderby_totalcorrect_exclude4 = path_e + 'experiencedResultExcludeTask4_orderby_total_correct_elements.csv'
file_experienced_orderby_age = path_e + 'experiencedResult_orderby_participant__age.csv'

# Inexperienced
path_in = 'inexperienced_participants/'
file_inexperienced_orderby_totaltime = path_in + 'nonExperiencedResult_orderby_totaltime.csv'
file_inexperienced_orderby_totaltime_exclude4 = path_in + 'inExperiencedResultExcludeTask4_orderby_totaltime.csv'
file_inexperienced_orderby_totalcorrect_exclude4 = path_in + 'inExperiencedResultExcludeTask4_orderby_total_correct_elements.csv'
file_inexperienced_orderby_age = path_in + 'nonExperiencedResult_orderby_participant__age.csv'

#Task
path_1 = 'task1/'
#       time
file_task1_orderedby_totaltime_all_not_interupted = path_1+'all_was_not_interupted_taskid1_orderby_taskresult__totaltime.csv'
file_task1_orderedby_totaltime_experienced_not_interupted = path_1+'experienced_was_not_interupted_task1_orderby_taskresult__totaltime.csv'
file_task1_orderedby_totaltime_inexperienced_not_interupted = path_1+'inexperienced_was_not_interupted_task1_orderby_taskresult__totaltime.csv'
#       correct
file_task1_orderedby_totalcorrect_all_not_interupted = path_1+'all_was_not_interupted_taskid1_orderby_taskresult__total_correct_elements.csv'
file_task1_orderedby_totalcorrect_experienced_not_interupted = path_1+'experienced_was_not_interupted_task1_orderby_taskresult__total_correct_elements.csv'
file_task1_orderedby_totalcorrect_inexpernced_not_interupted = path_1+'experienced_was_not_interupted_task1_orderby_taskresult__total_correct_elements.csv'

path_2 = 'task2/'
#       time
file_task2_orderedby_totaltime_all_not_interupted = path_2+'all_was_not_interupted_taskid2_orderby_taskresult__totaltime.csv'
file_task2_orderedby_totaltime_experienced_not_interupted = path_2+'experienced_was_not_interupted_task2_orderby_taskresult__totaltime.csv'
file_task2_orderedby_totaltime_inexperienced_not_interupted = path_2+'inexperienced_was_not_interupted_task2_orderby_taskresult__totaltime.csv'
#       correct
file_task2_orderedby_totalcorrect_all_not_interupted = path_2+'all_was_not_interupted_taskid2_orderby_taskresult__total_correct_elements.csv'
file_task2_orderedby_totalcorrect_experienced_not_interupted = path_2+'experienced_was_not_interupted_task2_orderby_taskresult__total_correct_elements.csv'
file_task2_orderedby_totalcorrect_inexperienced_not_inrupted = path_2+'experienced_was_not_interupted_task2_orderby_taskresult__total_correct_elements.csv'


path_3 = 'task3/'
#       time
file_task3_orderedby_totaltime_all_not_interupted = path_3+'all_was_not_interupted_taskid3_orderby_taskresult__totaltime.csv'
file_task3_orderedby_totaltime_experienced_not_interupted = path_3+'experienced_was_not_interupted_task3_orderby_taskresult__totaltime.csv'
file_task3_orderedby_totaltime_inexperienced_not_interupted = path_3+'inexperienced_was_not_interupted_task4_orderby_taskresult__totaltime.csv'
#       correct
file_task3_orderedby_totalcorrect_all_not_interupted = path_3+'all_was_not_interupted_taskid3_orderby_taskresult__total_correct_elements.csv'
file_task3_orderedby_totalcorrect_experienced_not_interupted = path_3+'experienced_was_not_interupted_task3_orderby_taskresult__total_correct_elements.csv'
file_task3_orderedby_totalcorrect_inexperienced_not_interupted = path_3+'inexperienced_was_not_interupted_task3_orderby_taskresult__total_correct_elements.csv'

# Task 1, 2, 3
file_task_1_2_3_totaltime = 'task_1_2_3_totaltime.csv'
file_task_1_2_3_correct = 'task123_correct.csv'

## OLD

#task1
file_task1_orderedby_totaltime = path_1+'oneElementTaskResult_filtertotaltime_totaltime.csv'
file_task1_orderedby_totaltime_experienced = path_1+'experiencedResult_task1_orderby_totaltime.csv'
file_task1_orderedby_totaltime_inexperienced = path_1+'inExperiencedResult_task1_orderby_totaltime.csv'


#task 2
file_task2_orderedby_totaltime = path_2+'threeElementTaskResult_filtertotaltime_totaltime.csv'
file_task2_orderedby_totaltime_experienced = path_2+'experiencedResult_task2_orderby_totaltime.csv'
file_task2_orderedby_totaltime_inexperienced = path_2+'inExperiencedResult_task2_orderby_totaltime.csv'

#task3
file_task3_orderedby_totaltime = path_3+'sixElementTaskResult_filtertotaltime_totaltime.csv'
file_task3_orderedby_totaltime_experienced = path_3+'experiencedResult_task3_orderby_totaltime.csv'
file_task3_orderedby_totaltime_inexperienced = path_3+'inExperiencedResult_task3_orderby_totaltime.csv'
